### ISSUE TITLE
Brightness Fix

### ISSUE THREAD

**Issue by King007t** [TzorriMahm/SNES_RGB_Bypass_Amp#1]
Does this board do the brightness fix on its own, or di I still have to replace the R3 resistor. 
And do I have to use CS ttl (cs.o raw) or CS 75 ohm (cs.o buff) from an super cic++ board.

Best regards

**Comment by TzorriMahm** [comment]
Yes, brightness fix is included. No need to change the value of R3.
You should use "CS.o raw" on borti's MultiRegion Mod and connect it to the "CS" Pad on the RGB amp.
Furthermore you don't have to lift Pin 7 of the SNES' S-RGB IC because you will completely bypass it.

**Comment by King007t** [comment]
Hi, i already changed the resistor with a 1.74kOhm resistor. Now the image is too dark. What was the original value so i can change it back?

**Comment by TzorriMahm** [comment]
Original value of R3 is 1.6k.
You could also remove R21, R31 and R41 on the amp instead.

**Comment by King007t** [comment]
The resistors arent there anyways. Its still to dim compared to my snes 3 chip

**Comment by TzorriMahm** [comment]
If R21/R31/R41 aren't populated you should swap R3 again. 

Are you using an RGB cable suitable for NTSC consoles?

**Comment by King007t** [comment]
So currently r3 is swapped to 1.74kOhm and the the 3 on the pcb arend populated. And somehow its a bit dimmer than original

**Comment by TzorriMahm** [comment]
That's correct.

And what kind of RGB cable do you use?

**Comment by King007t** [comment]
Its a attenuated csync ntsc from retrogamingcables. The one from the 3 chip is a sync on luma pal cable

**Comment by TzorriMahm** [comment]
Okay.
You say it's the correct cable, you did the brightness fix on R3.
There isn't much more in that circuit to mess with the R/G/B signals, except the THS.
Maybe the output resistors (R23/33/43) on the THS have the wrong value?

Otherwise I really don't know. Sorry.

Maybe a faulty THS or a dying S-SPUN (hopefully not). But that's a shot in the dark.

**Comment by King007t** [comment]
Hmm okay. I took some screenshots
SNES 1 chip: CSync
![Screenshot 2024-07-25 17-20-20](https://github.com/user-attachments/assets/999b9bce-233b-49d6-8217-7ca427116f19)
SNES 3 chip: Sync on Luma
![Screenshot 2024-07-25 17-21-21](https://github.com/user-attachments/assets/16fe5268-3aa7-473e-87fa-163f6434936f)

can this be because of sync on luma

**Comment by King007t** [comment]
And I remember my ebay seller told me to change R51 on your RGB Bypass AMP to 4.7k and R52 to 10.7k if i use dejitter, which i am doing. Could this change have maybe affected this? And was information even correct?

**Comment by TzorriMahm** [comment]
It's indeed dimmer than the 3-chip.
Changing values of R51 and R52 is correct when using de-jittered sync.

**Comment by markblokpoel** [comment]
> It's indeed dimmer than the 3-chip. Changing values of R51 and R52 is correct when using de-jittered sync.

Sorry to open up the issue again, but I'm planning to install the Marqs dejitter board with your RGB mod. Do I need to replace R51 and R52 as discussed here? Or can I leave the boards as provided. Thank you!
